/**
 * BD-I STORE & MATERIAL MANAGEMENT — Apps Script backend
 * ---------------------------------------------------------------
 * Deploy this as a Web App (Extensions > Apps Script > Deploy > New deployment
 * > type: Web app > Execute as: Me > Who has access: Anyone).
 * Paste the resulting /exec URL into the frontend's Settings tab.
 *
 * NUMBERING:
 *  - HR No. / Back HR No. (e.g. ISS/003/BD-I, RET/004/BD-I) is generated by
 *    THIS app automatically, resets every 1 January.
 *  - Voucher No. (e.g. ISS/000024/2025-2026) is generated by the separate
 *    government online system AFTER the HR/Back HR is issued, so it is
 *    entered manually here — either at the time of entry (if already known)
 *    or later via the "update voucher" action.
 *
 * MASTER DATA (kept in your own separate Google Sheet files, entered by you):
 *  - Master file (items + schemes): ONE file with two tabs. The "ItemMaster"
 *    tab has columns ItemCode | Description | Unit; the "SchemeMaster" tab has
 *    columns SchemeCode | SchemeName.
 *  - Work Order Master: ONE file, with one TAB PER CALENDAR YEAR (e.g. "2025",
 *    "2026"), each with columns AgencyName | WorkOrderNo | WorkOrderDate | NameOfWork
 *  Point this script at them (file IDs/URLs) via Script Properties — see
 *  "CONFIG / COUNTERS" below. This app never writes into these files.
 *
 * CONFIG / COUNTERS (Script Properties, NOT a sheet):
 *  MasterSheetId, WorkOrderMasterSheetId, and the running HR No. sequence
 *  numbers all live in this project's Script Properties instead of a
 *  spreadsheet tab, so they never touch the Transactions workbook at all.
 *  - To set the master file IDs: run the one-time setupMasterFileIds()
 *    function below (fill in the IDs/URLs first), OR add them directly
 *    under Apps Script editor > Project Settings (gear icon) > Script
 *    Properties, using keys cfg_MasterSheetId, cfg_WorkOrderMasterSheetId.
 *  - Counters are stored under keys like ctr_ISS_2026, ctr_RET_2026, etc.,
 *    and need no manual setup.
 *
 * YEAR-END ARCHIVING:
 *  Every time the script runs it moves any transaction rows dated before the
 *  current year out of the live "Transactions" tab and into per-year
 *  "Transactions_<year>" tabs (created automatically), so the live tab only
 *  ever holds the current year. This reconciles by row date, so it also
 *  rescues prior-year rows that were sitting in the live tab when the year
 *  counter was first set (or mid-year deploys happened) and handles skipped
 *  years in one pass. Reports/Register/Dashboard queries transparently read
 *  across the live tab AND all archived Transactions_* tabs, so nothing
 *  becomes invisible after the rollover.
 *
 * Sheets used in THIS workbook (auto-created on first run if missing):
 *   Transactions        - current year's transactions, one row per item line
 *   Transactions_<year> - previous years, created automatically at rollover
 *
 * PERFORMANCE / CACHING:
 *  Master data (items, schemes, work orders) is cached server-side (~30 min)
 *  so repeated calls don't re-read the external spreadsheets. The frontend
 *  additionally caches master data in the browser (localStorage) and searches
 *  work orders LOCALLY from a per-year index it downloads once — the server is
 *  only touched to warm a cache. Pass refresh=1 on an action to bypass the
 *  server cache; the frontend does this for its explicit refresh/sync buttons.
 */

const TXN_SHEET = 'Transactions';
const CONFIG_PREFIX = 'cfg_';
const COUNTER_PREFIX = 'ctr_';

/**
 * ONE-TIME SETUP: fill in your two master data file IDs/URLs below, then
 * open this project in the Apps Script editor, pick "setupMasterFileIds"
 * from the function dropdown at the top, and click Run once. (Re-run any
 * time you need to change one of these.)
 * MasterSheetId points at the file holding the "ItemMaster" and "SchemeMaster"
 * tabs (items + schemes). WorkOrderMasterSheetId is the separate work-order
 * file with one tab per calendar year.
 */
function setupMasterFileIds() {
  setConfigValue_('MasterSheetId', 'PASTE_MASTER_ID_OR_URL_HERE');
  setConfigValue_('WorkOrderMasterSheetId', 'PASTE_WORK_ORDER_MASTER_ID_OR_URL_HERE');
}

const TXN_HEADERS = [
  'SlNo', 'Date', 'TransactionType', 'HRNo', 'SchemeCode', 'SchemeName',
  'AgencyDetails', 'WorkOrderDetails', 'NameOfWork',
  'OfficeOrderNo', 'RoadChallanNo', 'ItemNo',
  'ItemCode', 'ItemDescription', 'Qty', 'Unit', 'VoucherNo'
];

const TX_TYPE_ISSUE = 'Issue';
const TX_TYPE_RECEIPT = 'Receipt';
const COL_DATE = TXN_HEADERS.indexOf('Date');
const COL_VOUCHER_NO = TXN_HEADERS.indexOf('VoucherNo');

function getSS() {
  return SpreadsheetApp.getActiveSpreadsheet();
}

function ensureSheet_(name, headers) {
  const ss = getSS();
  let sh = ss.getSheetByName(name);
  if (!sh) {
    sh = ss.insertSheet(name);
    if (headers) sh.appendRow(headers);
  }
  return sh;
}

/**
 * Non-fatal init: applies the one-time schema migration (drops the removed
 * CreatedAt column), archives the year if needed and ensures the live
 * Transactions tab exists. Never throws — a transient Script Properties or
 * spreadsheet hiccup must degrade to a JSON error (or a cache miss), never
 * to an HTML 500 that the frontend misreads as "backend unreachable".
 * Cache-first read actions skip this entirely and only call it when they
 * actually need to build from the sheets.
 */
function init_() {
  try { dropCreatedAtColumn_(); } catch (err) {}
  try { archiveYearIfNeeded_(); } catch (err) {}
  try { ensureSheet_(TXN_SHEET, TXN_HEADERS); } catch (err) {}
}

/**
 * One-time schema migration: the CreatedAt stamp column was removed, so any
 * transaction sheet (live or archived) that still carries a "CreatedAt"
 * header has that column deleted to keep all rows aligned with TXN_HEADERS.
 * Runs before year-end archiving so newly created archives are born clean.
 * Non-fatal by design (see init_()).
 */
function dropCreatedAtColumn_() {
  getAllTxnSheets_().forEach(function (sh) {
    const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
    const idx = headers.indexOf('CreatedAt');
    if (idx > -1) sh.deleteColumn(idx + 1);
  });
}

/* ---------------- Year-end archiving ---------------- */

/**
 * Archives any transaction rows dated before the current year into
 * Transactions_<year> tabs, keeping the live tab current-year-only.
 *
 * This reconciles by ROW YEAR rather than only on a tracked-year change, so
 * it also rescues prior-year rows that were sitting in the live tab when
 * CurrentTxnYear was first set (or a deploy happened mid-year): it will
 * split a mixed live tab into Transactions_2024 / Transactions_2025 / live,
 * and it handles multi-year gaps in one pass. Rows whose Date won't parse
 * are left in the live tab untouched. Non-fatal by design (see init_()).
 */
function archiveYearIfNeeded_() {
  const map = getConfigMap_();
  const currentYear = new Date().getFullYear();
  const trackedYear = Number(map['CurrentTxnYear']) || 0;
  const ss = getSS();
  const live = ss.getSheetByName(TXN_SHEET);
  if (!live) {
    if (!trackedYear) setConfigValue_('CurrentTxnYear', String(currentYear));
    return;
  }

  const data = live.getDataRange().getValues();
  const byYear = {};
  const toArchive = [];
  for (let i = 1; i < data.length; i++) {
    const d = new Date(data[i][COL_DATE]);
    const y = isNaN(d.getTime()) ? 0 : d.getFullYear();
    if (y && y < currentYear) {
      (byYear[y] = byYear[y] || []).push(i);
      toArchive.push(i);
    }
  }

  if (toArchive.length) {
    Object.keys(byYear).map(Number).sort(function (a, b) { return a - b; })
      .forEach(function (y) {
        const target = ensureSheet_(TXN_SHEET + '_' + y, TXN_HEADERS);
        const rows = byYear[y].map(function (i) { return data[i]; });
        target.getRange(target.getLastRow() + 1, 1, rows.length, rows[0].length).setValues(rows);
      });
    toArchive.sort(function (a, b) { return b - a; });
    toArchive.forEach(function (i) { live.deleteRow(i + 1); });
  }
  if (trackedYear !== currentYear) setConfigValue_('CurrentTxnYear', String(currentYear));
}

/* ---------------- Config (Script Properties) ---------------- */

function setConfigValue_(key, value) {
  PropertiesService.getScriptProperties().setProperty(CONFIG_PREFIX + key, value);
}

function getConfigMap_() {
  const props = PropertiesService.getScriptProperties().getProperties();
  const map = {};
  Object.keys(props).forEach(function (k) {
    if (k.indexOf(CONFIG_PREFIX) === 0) map[k.substring(CONFIG_PREFIX.length)] = props[k];
  });
  return map;
}

function getConfigValue_(key) {
  return PropertiesService.getScriptProperties().getProperty(CONFIG_PREFIX + key) || '';
}

function extractSheetId_(idOrUrl) {
  if (!idOrUrl) return '';
  const m = idOrUrl.match(/\/d\/([a-zA-Z0-9-_]+)/);
  return m ? m[1] : idOrUrl;
}

/**
 * Opens an external spreadsheet by ID (or full URL). Tries a tab named
 * `preferredTabName` first, falls back to the first tab. Returns null if
 * the id is blank or the file/tab can't be opened.
 */
function openExternalTab_(idOrUrl, preferredTabName) {
  if (!idOrUrl) return null;
  try {
    const ss = SpreadsheetApp.openById(extractSheetId_(idOrUrl));
    return ss.getSheetByName(preferredTabName) || ss.getSheets()[0];
  } catch (err) {
    return null;
  }
}

function sheetRowsAsObjects_(sh) {
  if (!sh) return [];
  const data = sh.getDataRange().getValues();
  if (data.length < 2) return [];
  const headers = data[0].map(h => String(h).trim());
  const rows = [];
  for (let i = 1; i < data.length; i++) {
    const row = data[i];
    if (!row.some(c => c !== '' && c !== null)) continue;
    const obj = {};
    Object.defineProperty(obj, '__row', { value: i + 1, enumerable: false, writable: true });
    headers.forEach((h, j) => obj[h] = row[j]);
    rows.push(obj);
  }
  return rows;
}

/* ---------------- Server-side cache (fast reads) ---------------- */

const CACHE_TTL_SEC = 1800;      // 30 min; Apps Script CacheService max is 6h
const SREG_VER_TTL_SEC = 21600;  // 6h — the sreg version counter outlives payload TTLs
const CACHE_KEY_DASH = 'dash_v2';  // bump when the dashboard payload shape changes
const CACHE_KEY_META = 'meta_v1';
const SREG_VER_KEY = 'sreg_ver';

function cacheGet_(key) {
  try { return CacheService.getScriptCache().get(key); } catch (err) { return null; }
}
function cachePut_(key, value) {
  try { CacheService.getScriptCache().put(key, value, CACHE_TTL_SEC); } catch (err) {}
}
function cacheDrop_(key) {
  try { CacheService.getScriptCache().remove(key); } catch (err) {}
}

/* Versioned cache namespace so one write invalidates all stockRegister reads. */
function sregVersion_() {
  return cacheGet_(SREG_VER_KEY) || '1';
}
function bumpSregVersion_() {
  cachePut_(SREG_VER_KEY, String(Number(sregVersion_()) + 1), SREG_VER_TTL_SEC);
}

/** Every write must invalidate the cached reads (dashboard + stock register). */
function invalidateReadCaches_() {
  cacheDrop_(CACHE_KEY_DASH);
  bumpSregVersion_();
}

/**
 * Standard cache-first read: serve the payload from CacheService when present
 * (unless `bypass` — i.e. refresh=1), otherwise build it fresh, store it and
 * return. init_() only runs on the build path so cached requests stay cheap.
 */
function withCache_(cacheKey, bypass, buildFn) {
  if (!bypass) {
    const hit = cacheGet_(cacheKey);
    if (hit) {
      try { return JSON.parse(hit); } catch (err) {}
    }
  }
  init_();
  const result = buildFn();
  cachePut_(cacheKey, JSON.stringify(result));
  return result;
}

/* ---------------- CORS / entry points ---------------- */

function doGet(e) {
  try {
    const action = e.parameter.action || 'list';
    let result;
    switch (action) {
      case 'list':
        init_();
        result = listTransactions_(e.parameter);
        break;
      case 'stockRegister':
        result = stockRegister_(e.parameter);
        break;
      case 'filterOptions':
        result = filterOptions_(e.parameter);
        break;
      case 'meta':
        result = getMeta_(e.parameter.refresh === '1');
        break;
      case 'workOrderIndex':
        result = workOrderIndex_(e.parameter);
        break;
      case 'workOrders':
        init_();
        result = searchWorkOrders_(e.parameter);
        break;
      case 'dashboard':
        result = getDashboard_(e.parameter.refresh === '1');
        break;
      default:
        result = { error: 'Unknown action: ' + action };
    }
    return jsonOut_(result);
  } catch (err) {
    return jsonOut_({ error: err.message });
  }
}

function doPost(e) {
  try {
    init_();
    const body = JSON.parse(e.postData.contents);
    const action = body.action;
    let result;
    switch (action) {
      case 'addTransaction':
        result = addTransaction_(body);
        break;
      case 'updateVoucher':
        result = updateVoucher_(body);
        break;
      default:
        result = { error: 'Unknown action: ' + action };
    }
    return jsonOut_(result);
  } catch (err) {
    return jsonOut_({ error: err.message });
  }
}

function jsonOut_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

/* ---------------- HR No. numbering (auto) ---------------- */

function pad_(n, width) {
  return String(n).padStart(width, '0');
}

/* ---------------- Counters (Script Properties) ---------------- */

function nextSeq_(key) {
  const lock = LockService.getScriptLock();
  lock.waitLock(30000); // serialize counter bumps across concurrent requests
  try {
    const props = PropertiesService.getScriptProperties();
    const propKey = COUNTER_PREFIX + key;
    const next = (Number(props.getProperty(propKey)) || 0) + 1;
    props.setProperty(propKey, String(next));
    return next;
  } finally {
    lock.releaseLock();
  }
}

/**
 * type: 'Issue' | 'Receipt'. Generates the HR No. / Back HR No. only.
 * Voucher No. is NOT generated here — it's entered manually (see addTransaction_).
 */
function generateHrNo_(type, dateObj) {
  const calYear = dateObj.getFullYear();
  const prefix = (type === TX_TYPE_ISSUE) ? 'ISS' : 'RET';
  const hrSeq = nextSeq_('HR_' + type + '_' + calYear);
  return prefix + '/' + pad_(hrSeq, 3) + '/BD-I';
}

/* ---------------- Write ---------------- */

/**
 * body = {
 *   action: 'addTransaction',
 *   date: 'YYYY-MM-DD',
 *   transactionType: 'Issue' | 'Receipt',
 *   schemeCode, schemeName,
 *   agencyDetails, workOrderDetails, nameOfWork,
 *   officeOrderNo, roadChallanNo,
 *   voucherNo,   // optional — fill in now if already known, or leave blank
 *   items: [{ itemCode, itemDescription, qty, unit }, ...]
 * }
 * Always writes to the CURRENT (live) Transactions tab.
 */
function addTransaction_(body) {
  if (!body.items || !body.items.length) throw new Error('At least one item line is required.');
  const sh = ensureSheet_(TXN_SHEET, TXN_HEADERS);
  const hrNo = generateHrNo_(body.transactionType, new Date(body.date + 'T00:00:00'));
  let slNo = Math.max(0, sh.getLastRow() - 1);

  const rows = body.items.map(function (it, idx) {
    slNo += 1;
    return buildTxnRow_({
      SlNo: slNo,
      Date: body.date,
      TransactionType: body.transactionType,
      HRNo: hrNo,
      SchemeCode: body.schemeCode,
      SchemeName: body.schemeName,
      AgencyDetails: body.agencyDetails,
      WorkOrderDetails: body.workOrderDetails,
      NameOfWork: body.nameOfWork,
      OfficeOrderNo: body.officeOrderNo,
      RoadChallanNo: body.roadChallanNo,
      ItemNo: idx + 1,
      ItemCode: it.itemCode,
      ItemDescription: it.itemDescription,
      Qty: Number(it.qty) || 0,
      Unit: it.unit,
      VoucherNo: body.voucherNo
    });
  });

  sh.getRange(sh.getLastRow() + 1, 1, rows.length, TXN_HEADERS.length).setValues(rows);
  invalidateReadCaches_();

  return { success: true, hrNo: hrNo, voucherNo: body.voucherNo || '', lines: rows.length };
}

/**
 * Aligns a named set of transaction values to the TXN_HEADERS column order,
 * so column renames/reorders only need a change in TXN_HEADERS.
 */
function buildTxnRow_(values) {
  return TXN_HEADERS.map(function (header) {
    return values[header] == null ? '' : values[header];
  });
}

/**
 * body = { action: 'updateVoucher', hrNo, voucherNo }
 * Fills in the Voucher No. (received later from the online system) for
 * every line already saved under a given HR No. Searches the live tab and
 * all archived Transactions_<year> tabs.
 */
function updateVoucher_(body) {
  if (!body.hrNo || !body.voucherNo) throw new Error('hrNo and voucherNo are both required.');
  const sheets = getAllTxnSheets_();
  const col = COL_VOUCHER_NO + 1;
  let updated = 0;
  sheets.forEach(function (sh) {
    const rows = sheetRowsAsObjects_(sh);
    rows.forEach(function (r) {
      if (r['HRNo'] === body.hrNo) {
        sh.getRange(r.__row + 1, col).setValue(body.voucherNo);
        updated++;
      }
    });
  });
  if (!updated) throw new Error('No transaction found with HR No. ' + body.hrNo);
  invalidateReadCaches_();
  return { success: true, updated: updated };
}

/* ---------------- Read ---------------- */

/** All transaction sheets: the live "Transactions" tab plus any "Transactions_<year>" archives. */
function getAllTxnSheets_() {
  const ss = getSS();
  return ss.getSheets().filter(sh =>
    sh.getName() === TXN_SHEET || /^Transactions_\d{4}$/.test(sh.getName())
  );
}

function getAllTxns_() {
  return getAllTxnSheets_().reduce(function (acc, sh) {
    return acc.concat(sheetRowsAsObjects_(sh));
  }, []);
}

function listTransactions_(params) {
  const rows = applyFilters_(getAllTxns_(), params);
  rows.sort(byNewest);
  return { rows: rows, count: rows.length };
}

/** Case-insensitive substring match; missing values never match. */
function containsText_(value, query) {
  return String(value || '').toLowerCase().indexOf(query) > -1;
}

function applyFilters_(rows, params) {
  if (params.from) {
    const from = new Date(params.from);
    rows = rows.filter(function (r) { return new Date(r.Date) >= from; });
  }
  if (params.to) {
    const to = new Date(params.to);
    rows = rows.filter(function (r) { return new Date(r.Date) <= to; });
  }
  if (params.type) {
    rows = rows.filter(function (r) { return r.TransactionType === params.type; });
  }
  if (params.schemeCode) {
    rows = rows.filter(function (r) { return r.SchemeCode === params.schemeCode; });
  }
  if (params.itemCode) {
    rows = rows.filter(function (r) { return r.ItemCode === params.itemCode; });
  }
  if (params.noVoucherOnly === 'true') {
    rows = rows.filter(function (r) { return !r.VoucherNo; });
  }
  if (params.agency) {
    const q = params.agency.toLowerCase();
    rows = rows.filter(function (r) { return containsText_(r.AgencyDetails, q); });
  }
  if (params.workOrder) {
    const q = params.workOrder.toLowerCase();
    rows = rows.filter(function (r) { return containsText_(r.WorkOrderDetails, q); });
  }
  if (params.q) {
    const q = params.q.toLowerCase();
    rows = rows.filter(function (r) {
      return containsText_(r.AgencyDetails, q) ||
        containsText_(r.WorkOrderDetails, q) ||
        containsText_(r.NameOfWork, q) ||
        containsText_(r.ItemDescription, q) ||
        containsText_(r.HRNo, q) ||
        containsText_(r.VoucherNo, q);
    });
  }
  return rows;
}

/**
 * Stock register: opening balance (as of day before "from") + receipts - issues
 * within [from, to], per item. If itemCode given, restrict to that item.
 * Reads across the live tab and all archived year tabs, so balances stay
 * correct across a calendar-year rollover.
 * Results are cached server-side keyed by from|to|itemCode; the cache is
 * invalidated (version bump) on every write so it stays correct.
 * refresh=1 bypasses the cache read.
 */
function stockRegister_(params) {
  const cacheKey = 'sreg_v' + sregVersion_() + '_' +
    [params.from || '', params.to || '', params.itemCode || ''].join('|');
  return withCache_(cacheKey, params.refresh === '1', function () {
    return buildStockRegister_(params);
  });
}

/** Sort comparator: newest Date first, ties broken by highest SlNo first. */
function byNewest(a, b) {
  return new Date(b.Date) - new Date(a.Date) || b.SlNo - a.SlNo;
}

/** True when d is inside [from, to]; either bound may be null (open-ended). */
function isInRange_(d, from, to) {
  return (!from || d >= from) && (!to || d <= to);
}

function buildStockRegister_(params) {
  const rows = getAllTxns_();
  const from = params.from ? new Date(params.from) : null;
  const to = params.to ? new Date(params.to) : null;

  const byItem = {};
  rows.forEach(function (r) {
    if (params.itemCode && r.ItemCode !== params.itemCode) return;
    const key = r.ItemCode;
    if (!byItem[key]) {
      byItem[key] = {
        itemCode: r.ItemCode,
        description: r.ItemDescription,
        unit: r.Unit,
        opening: 0,
        received: 0,
        issued: 0,
        closing: 0,
        movements: []
      };
    }
    const d = new Date(r.Date);
    const qty = Number(r.Qty) || 0;
    const signed = (r.TransactionType === TX_TYPE_RECEIPT) ? qty : -qty;

    if (from && d < from) {
      byItem[key].opening += signed;
    } else if (isInRange_(d, from, to)) {
      if (r.TransactionType === TX_TYPE_RECEIPT) byItem[key].received += qty;
      else byItem[key].issued += qty;
      byItem[key].movements.push({
        date: r.Date, type: r.TransactionType, hrNo: r.HRNo, voucherNo: r.VoucherNo,
        agency: r.AgencyDetails, qty: qty
      });
    }
  });

  Object.keys(byItem).forEach(function (k) {
    const it = byItem[k];
    it.closing = it.opening + it.received - it.issued;
    it.movements.sort(function (a, b) { return new Date(a.date) - new Date(b.date); });
  });

  return { items: Object.values(byItem) };
}

/* ---------------- Filter options (transaction-derived dropdown values) ---------------- */

/**
 * Distinct values actually present in the transaction sheets, for the
 * movement-report / register dropdowns. Only values that have really been
 * transacted are offered — the master files (work orders, schemes) contain
 * far more than what the store has touched.
 * params: { refresh: '1' }.
 * Cached namespaced by sreg_ver so any write invalidates it (same rule as
 * the stock register).
 */
function filterOptions_(params) {
  const cacheKey = 'fopts_v' + sregVersion_() + '_all';
  return withCache_(cacheKey, params.refresh === '1', buildFilterOptions_);
}

function buildFilterOptions_() {
  const rows = getAllTxns_();
  const agencies = new Set();
  const workOrders = new Set();
  const schemes = {};
  rows.forEach(function (r) {
    const agency = String(r.AgencyDetails || '').trim();
    if (agency) agencies.add(agency);
    const wo = String(r.WorkOrderDetails || '').trim();
    if (wo) workOrders.add(wo);
    const code = String(r.SchemeCode || '').trim();
    if (code) schemes[code] = String(r.SchemeName || '');
  });
  const byName = function (a, b) { return a.localeCompare(b); };
  return {
    agencies: Array.from(agencies).sort(byName),
    workOrders: Array.from(workOrders).sort(byName),
    schemes: Object.keys(schemes).sort(byName).map(function (code) {
      return { schemeCode: code, schemeName: schemes[code] };
    })
  };
}

/* ---------------- Master data (external files, read-only) ---------------- */

function getMeta_(force) {
  return withCache_(CACHE_KEY_META, force, buildMeta_);
}

function buildMeta_() {
  const cfg = getConfigMap_();

  // Items and schemes share one master file (tabs "ItemMaster" / "SchemeMaster").
  // Falls back to the old separate-file keys until they've been replaced.
  const masterId = cfg['MasterSheetId'];

  const itemTab = openExternalTab_(masterId || cfg['ItemMasterSheetId'], 'ItemMaster');
  const items = itemTab
    ? sheetRowsAsObjects_(itemTab)
        .map(r => ({ itemCode: r['ItemCode'], description: r['Description'], unit: r['Unit'] }))
        .filter(i => i.itemCode)
    : [];

  const schemeTab = openExternalTab_(masterId || cfg['SchemeMasterSheetId'], 'SchemeMaster');
  const schemes = schemeTab
    ? sheetRowsAsObjects_(schemeTab)
        .map(r => ({ schemeCode: r['SchemeCode'], schemeName: r['SchemeName'] }))
        .filter(s => s.schemeCode)
    : [];

  return { items: items, schemes: schemes, workOrderYears: getWorkOrderYears_(cfg) };
}

/** Calendar-year tabs (e.g. "2024", "2025", "2026") present in the Work Order Master file. */
function getWorkOrderYears_(cfg) {
  const id = cfg['WorkOrderMasterSheetId'];
  if (!id) return [];
  try {
    const ss = SpreadsheetApp.openById(extractSheetId_(id));
    return ss.getSheets()
      .map(s => s.getName())
      .filter(n => /^\d{4}$/.test(n))
      .sort()
      .reverse();
  } catch (err) {
    return [];
  }
}

/**
 * Returns ALL work-order rows for a calendar-year tab (no free-text filter).
 * The frontend downloads this once per year and searches it LOCALLY for
 * instant search. params: { year: '2026', refresh: '1' }.
 * Same row shape as searchWorkOrders_(), but unfiltered and cached.
 */
function workOrderIndex_(params) {
  const year = params.year;
  if (!year) throw new Error('year (calendar year, e.g. 2026) is required.');
  const tab = openWorkOrderTab_(String(year));
  if (!tab) return { rows: [], note: 'No tab named "' + year + '" found in the Work Order Master file.' };

  const cacheKey = 'woidx_' + year + '_v1';
  return withCache_(cacheKey, params.refresh === '1', function () {
    const rows = sheetRowsAsObjects_(tab)
      .map(function (r) {
        return {
          AgencyName: r['AgencyName'],
          WorkOrderNo: r['WorkOrderNo'],
          WorkOrderDate: r['WorkOrderDate'],
          NameOfWork: r['NameOfWork']
        };
      })
      .filter(function (r) { return r.WorkOrderNo; });
    return { rows: rows };
  });
}

/** Opens the given calendar-year tab of the Work Order Master, or null when missing/unconfigured. */
function openWorkOrderTab_(year) {
  const id = getConfigValue_('WorkOrderMasterSheetId');
  return id ? openExternalTab_(id, year) : null;
}

/**
 * Searches the calendar-year tab of the Work Order Master file for rows
 * matching a free-text query against agency name or work order no.
 * params: { year: '2026', q: 'jogmaya' }
 * Expected columns in each year's tab: AgencyName, WorkOrderNo, WorkOrderDate, NameOfWork
 * Kept as a fallback for the frontend when the local index can't load.
 */
function searchWorkOrders_(params) {
  const year = params.year;
  if (!year) throw new Error('year (calendar year, e.g. 2026) is required.');
  const tab = openWorkOrderTab_(String(year));
  if (!tab) return { rows: [], note: 'No tab named "' + year + '" found in the Work Order Master file.' };

  let rows = sheetRowsAsObjects_(tab);
  if (params.q) {
    const q = params.q.toLowerCase();
    rows = rows.filter(function (r) {
      return containsText_(r['AgencyName'], q) ||
        containsText_(r['WorkOrderNo'], q) ||
        containsText_(r['NameOfWork'], q);
    });
  }
  return { rows: rows.slice(0, 20) };
}

/* ---------------- Dashboard ---------------- */

function getDashboard_(force) {
  return withCache_(CACHE_KEY_DASH, force, buildDashboard_);
}

function buildDashboard_() {
  const rows = getAllTxns_();
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const month = tallyMonth_(rows, monthStart);
  const yearHrs = tallyYearHrs_(rows, now.getFullYear());
  const position = tallyStockPosition_(rows);
  return {
    monthIssuedQty: month.issuedQty, monthReceivedQty: month.receivedQty,
    monthIssuedLines: month.issuedLines, monthReceivedLines: month.receivedLines,
    yearIssuedHrs: yearHrs.issued, yearReceivedHrs: yearHrs.received,
    positiveStock: position.positive, negativeStock: position.negative,
    totalTxns: rows.length,
    pendingVoucher: rows.filter(function (r) { return !r.VoucherNo; }).length,
    recent: rows.slice().sort(byNewest).slice(0, 8)
  };
}

/** Quantities and line counts for the current month, split by transaction type. */
function tallyMonth_(rows, monthStart) {
  let issuedQty = 0, receivedQty = 0, issuedLines = 0, receivedLines = 0;
  rows.forEach(function (r) {
    if (new Date(r.Date) >= monthStart) {
      if (r.TransactionType === TX_TYPE_ISSUE) { issuedQty += Number(r.Qty) || 0; issuedLines++; }
      else { receivedQty += Number(r.Qty) || 0; receivedLines++; }
    }
  });
  return {
    issuedQty: issuedQty, receivedQty: receivedQty,
    issuedLines: issuedLines, receivedLines: receivedLines
  };
}

/** Distinct HR nos. transacted in the given calendar year, split by type. */
function tallyYearHrs_(rows, year) {
  const issued = new Set(), received = new Set();
  rows.forEach(function (r) {
    if (new Date(r.Date).getFullYear() !== year) return;
    if (r.TransactionType === TX_TYPE_ISSUE) issued.add(String(r.HRNo));
    else if (r.TransactionType === TX_TYPE_RECEIPT) received.add(String(r.HRNo));
  });
  return { issued: issued.size, received: received.size };
}

/** Counts of materials with all-time closing stock above/below zero. */
function tallyStockPosition_(rows) {
  const stock = {};
  rows.forEach(function (r) {
    const qty = Number(r.Qty) || 0;
    stock[r.ItemCode] = (stock[r.ItemCode] || 0) + (r.TransactionType === TX_TYPE_RECEIPT ? qty : -qty);
  });
  let positive = 0, negative = 0;
  Object.keys(stock).forEach(function (k) {
    if (stock[k] > 0) positive++;
    else if (stock[k] < 0) negative++;
  });
  return { positive: positive, negative: negative };
}
