/**
 * BD-I STORE & MATERIAL MANAGEMENT — Apps Script backend
 * ---------------------------------------------------------------
 * Deploy this as a Web App (Extensions > Apps Script > Deploy > New deployment
 * > type: Web app > Execute as: Me > Who has access: Anyone).
 * Paste the resulting /exec URL into the frontend's Settings tab.
 *
 * NUMBERING:
 *  - HR No. / Back HR No. (e.g. ISS/003/BD-I, RET/004/BD-I) is generated by
 *    THIS app automatically, resets every 1 January.
 *  - Voucher No. (e.g. ISS/000024/2025-2026) is generated by the separate
 *    government online system AFTER the HR/Back HR is issued, so it is
 *    entered manually here — either at the time of entry (if already known)
 *    or later via the "update voucher" action.
 *
 * MASTER DATA (kept in your own separate Google Sheet files, entered by you):
 *  - ItemMaster file: columns ItemCode | Description | Unit
 *  - SchemeMaster file: columns SchemeCode | SchemeName
 *  - Work Order Master: ONE file, with one TAB PER CALENDAR YEAR (e.g. "2025",
 *    "2026"), each with columns AgencyName | WorkOrderNo | WorkOrderDate | NameOfWork
 *  Point this script at them (file IDs/URLs) via Script Properties — see
 *  "CONFIG / COUNTERS" below. This app never writes into these files.
 *
 * CONFIG / COUNTERS (Script Properties, NOT a sheet):
 *  ItemMasterSheetId, SchemeMasterSheetId, WorkOrderMasterSheetId, and the
 *  running HR No. sequence numbers all live in this project's Script
 *  Properties instead of a spreadsheet tab, so they never touch the
 *  Transactions workbook at all.
 *  - To set the master file IDs: run the one-time setupMasterFileIds()
 *    function below (fill in the IDs/URLs first), OR add them directly
 *    under Apps Script editor > Project Settings (gear icon) > Script
 *    Properties, using keys cfg_ItemMasterSheetId, cfg_SchemeMasterSheetId,
 *    cfg_WorkOrderMasterSheetId.
 *  - Counters are stored under keys like ctr_ISS_2026, ctr_RET_2026, etc.,
 *    and need no manual setup.
 *
 * YEAR-END ARCHIVING:
 *  Every time the script runs it moves any transaction rows dated before the
 *  current year out of the live "Transactions" tab and into per-year
 *  "Transactions_<year>" tabs (created automatically), so the live tab only
 *  ever holds the current year. This reconciles by row date, so it also
 *  rescues prior-year rows that were sitting in the live tab when the year
 *  counter was first set (or mid-year deploys happened) and handles skipped
 *  years in one pass. Reports/Register/Dashboard queries transparently read
 *  across the live tab AND all archived Transactions_* tabs, so nothing
 *  becomes invisible after the rollover.
 *
 * Sheets used in THIS workbook (auto-created on first run if missing):
 *   Transactions        - current year's transactions, one row per item line
 *   Transactions_<year> - previous years, created automatically at rollover
 *
 * PERFORMANCE / CACHING:
 *  Master data (items, schemes, work orders) is cached server-side (~30 min)
 *  so repeated calls don't re-read the external spreadsheets. The frontend
 *  additionally caches master data in the browser (localStorage) and searches
 *  work orders LOCALLY from a per-year index it downloads once — the server is
 *  only touched to warm a cache. Pass refresh=1 on an action to bypass the
 *  server cache; the frontend does this for its explicit refresh/sync buttons.
 */

const TXN_SHEET = 'Transactions';
const CONFIG_PREFIX = 'cfg_';
const COUNTER_PREFIX = 'ctr_';

/**
 * ONE-TIME SETUP: fill in your three master data file IDs/URLs below, then
 * open this project in the Apps Script editor, pick "setupMasterFileIds"
 * from the function dropdown at the top, and click Run once. (Re-run any
 * time you need to change one of these.)
 */
function setupMasterFileIds() {
  setConfigValue_('ItemMasterSheetId', 'PASTE_ITEM_MASTER_ID_OR_URL_HERE');
  setConfigValue_('SchemeMasterSheetId', 'PASTE_SCHEME_MASTER_ID_OR_URL_HERE');
  setConfigValue_('WorkOrderMasterSheetId', 'PASTE_WORK_ORDER_MASTER_ID_OR_URL_HERE');
}

const TXN_HEADERS = [
  'SlNo', 'Date', 'TransactionType', 'HRNo', 'SchemeCode', 'SchemeName',
  'AgencyDetails', 'WorkOrderDetails', 'NameOfWork',
  'OfficeOrderNo', 'RoadChallanNo', 'ItemNo',
  'ItemCode', 'ItemDescription', 'Qty', 'Unit', 'VoucherNo', 'CreatedAt'
];

function getSS() {
  return SpreadsheetApp.getActiveSpreadsheet();
}

function ensureSheet_(name, headers) {
  const ss = getSS();
  let sh = ss.getSheetByName(name);
  if (!sh) {
    sh = ss.insertSheet(name);
    if (headers) sh.appendRow(headers);
  }
  return sh;
}

/**
 * Non-fatal init: archives the year if needed and ensures the live
 * Transactions tab exists. Never throws — a transient Script Properties or
 * spreadsheet hiccup must degrade to a JSON error (or a cache miss), never
 * to an HTML 500 that the frontend misreads as "backend unreachable".
 * Cache-first read actions skip this entirely and only call it when they
 * actually need to build from the sheets.
 */
function init_() {
  try { archiveYearIfNeeded_(); } catch (err) {}
  try { ensureSheet_(TXN_SHEET, TXN_HEADERS); } catch (err) {}
}

/* ---------------- Year-end archiving ---------------- */

/**
 * Archives any transaction rows dated before the current year into
 * Transactions_<year> tabs, keeping the live tab current-year-only.
 *
 * This reconciles by ROW YEAR rather than only on a tracked-year change, so
 * it also rescues prior-year rows that were sitting in the live tab when
 * CurrentTxnYear was first set (or a deploy happened mid-year): it will
 * split a mixed live tab into Transactions_2024 / Transactions_2025 / live,
 * and it handles multi-year gaps in one pass. Rows whose Date won't parse
 * are left in the live tab untouched. Non-fatal by design (see init_()).
 */
function archiveYearIfNeeded_() {
  const map = getConfigMap_();
  const currentYear = new Date().getFullYear();
  const trackedYear = Number(map['CurrentTxnYear']) || 0;
  const ss = getSS();
  const live = ss.getSheetByName(TXN_SHEET);
  if (!live) {
    if (!trackedYear) setConfigValue_('CurrentTxnYear', String(currentYear));
    return;
  }

  const data = live.getDataRange().getValues();
  const byYear = {};
  const toArchive = [];
  for (let i = 1; i < data.length; i++) {
    const d = new Date(data[i][1]);
    const y = isNaN(d.getTime()) ? 0 : d.getFullYear();
    if (y && y < currentYear) {
      (byYear[y] = byYear[y] || []).push(i);
      toArchive.push(i);
    }
  }

  if (toArchive.length) {
    Object.keys(byYear).map(Number).sort(function (a, b) { return a - b; })
      .forEach(function (y) {
        const target = ensureSheet_(TXN_SHEET + '_' + y, TXN_HEADERS);
        const rows = byYear[y].map(function (i) { return data[i]; });
        target.getRange(target.getLastRow() + 1, 1, rows.length, rows[0].length).setValues(rows);
      });
    toArchive.sort(function (a, b) { return b - a; });
    toArchive.forEach(function (i) { live.deleteRow(i + 1); });
  }
  if (trackedYear !== currentYear) setConfigValue_('CurrentTxnYear', String(currentYear));
}

/* ---------------- Config (Script Properties) ---------------- */

function setConfigValue_(key, value) {
  PropertiesService.getScriptProperties().setProperty(CONFIG_PREFIX + key, value);
}

function getConfigMap_() {
  const props = PropertiesService.getScriptProperties().getProperties();
  const map = {};
  Object.keys(props).forEach(function (k) {
    if (k.indexOf(CONFIG_PREFIX) === 0) map[k.substring(CONFIG_PREFIX.length)] = props[k];
  });
  return map;
}

function getConfigValue_(key) {
  return PropertiesService.getScriptProperties().getProperty(CONFIG_PREFIX + key) || '';
}

function extractSheetId_(idOrUrl) {
  if (!idOrUrl) return '';
  const m = idOrUrl.match(/\/d\/([a-zA-Z0-9-_]+)/);
  return m ? m[1] : idOrUrl;
}

/**
 * Opens an external spreadsheet by ID (or full URL). Tries a tab named
 * `preferredTabName` first, falls back to the first tab. Returns null if
 * the id is blank or the file/tab can't be opened.
 */
function openExternalTab_(idOrUrl, preferredTabName) {
  if (!idOrUrl) return null;
  try {
    const ss = SpreadsheetApp.openById(extractSheetId_(idOrUrl));
    return ss.getSheetByName(preferredTabName) || ss.getSheets()[0];
  } catch (err) {
    return null;
  }
}

function sheetRowsAsObjects_(sh) {
  if (!sh) return [];
  const data = sh.getDataRange().getValues();
  if (data.length < 2) return [];
  const headers = data[0].map(h => String(h).trim());
  const rows = [];
  for (let i = 1; i < data.length; i++) {
    const row = data[i];
    if (!row.some(c => c !== '' && c !== null)) continue;
    const obj = {};
    Object.defineProperty(obj, '__row', { value: i + 1, enumerable: false, writable: true });
    headers.forEach((h, j) => obj[h] = row[j]);
    rows.push(obj);
  }
  return rows;
}

/* ---------------- Server-side cache (fast reads) ---------------- */

const CACHE_TTL_SEC = 1800;      // 30 min; Apps Script CacheService max is 6h
const SREG_VER_TTL_SEC = 21600;  // 6h — the sreg version counter outlives payload TTLs
const CACHE_KEY_DASH = 'dash_v2';  // bump when the dashboard payload shape changes
const CACHE_KEY_META = 'meta_v1';
const SREG_VER_KEY = 'sreg_ver';

function cacheGet_(key) {
  try { return CacheService.getScriptCache().get(key); } catch (err) { return null; }
}
function cachePut_(key, value) {
  try { CacheService.getScriptCache().put(key, value, CACHE_TTL_SEC); } catch (err) {}
}
function cacheDrop_(key) {
  try { CacheService.getScriptCache().remove(key); } catch (err) {}
}

/* Versioned cache namespace so one write invalidates all stockRegister reads. */
function sregVersion_() {
  return cacheGet_(SREG_VER_KEY) || '1';
}
function bumpSregVersion_() {
  cachePut_(SREG_VER_KEY, String(Number(sregVersion_()) + 1), SREG_VER_TTL_SEC);
}

/** Every write must invalidate the cached reads (dashboard + stock register). */
function invalidateReadCaches_() {
  cacheDrop_(CACHE_KEY_DASH);
  bumpSregVersion_();
}

/**
 * Standard cache-first read: serve the payload from CacheService when present
 * (unless `bypass` — i.e. refresh=1), otherwise build it fresh, store it and
 * return. init_() only runs on the build path so cached requests stay cheap.
 */
function withCache_(cacheKey, bypass, buildFn) {
  if (!bypass) {
    const hit = cacheGet_(cacheKey);
    if (hit) {
      try { return JSON.parse(hit); } catch (err) {}
    }
  }
  init_();
  const result = buildFn();
  cachePut_(cacheKey, JSON.stringify(result));
  return result;
}

/* ---------------- CORS / entry points ---------------- */

function doGet(e) {
  try {
    const action = e.parameter.action || 'list';
    let result;
    switch (action) {
      case 'list':
        init_();
        result = listTransactions_(e.parameter);
        break;
      case 'stockRegister':
        result = stockRegister_(e.parameter);
        break;
      case 'filterOptions':
        result = filterOptions_(e.parameter);
        break;
      case 'meta':
        result = getMeta_(e.parameter.refresh === '1');
        break;
      case 'workOrderIndex':
        result = workOrderIndex_(e.parameter);
        break;
      case 'workOrders':
        init_();
        result = searchWorkOrders_(e.parameter);
        break;
      case 'dashboard':
        result = getDashboard_(e.parameter.refresh === '1');
        break;
      default:
        result = { error: 'Unknown action: ' + action };
    }
    return jsonOut_(result);
  } catch (err) {
    return jsonOut_({ error: err.message });
  }
}

function doPost(e) {
  try {
    init_();
    const body = JSON.parse(e.postData.contents);
    const action = body.action;
    let result;
    switch (action) {
      case 'addTransaction':
        result = addTransaction_(body);
        break;
      case 'updateVoucher':
        result = updateVoucher_(body);
        break;
      default:
        result = { error: 'Unknown action: ' + action };
    }
    return jsonOut_(result);
  } catch (err) {
    return jsonOut_({ error: err.message });
  }
}

function jsonOut_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

/* ---------------- HR No. numbering (auto) ---------------- */

function pad_(n, width) {
  n = String(n);
  while (n.length < width) n = '0' + n;
  return n;
}

/* ---------------- Counters (Script Properties) ---------------- */

function nextSeq_(key) {
  const lock = LockService.getScriptLock();
  lock.waitLock(30000); // serialize counter bumps across concurrent requests
  try {
    const props = PropertiesService.getScriptProperties();
    const propKey = COUNTER_PREFIX + key;
    const next = (Number(props.getProperty(propKey)) || 0) + 1;
    props.setProperty(propKey, String(next));
    return next;
  } finally {
    lock.releaseLock();
  }
}

/**
 * type: 'Issue' | 'Receipt'. Generates the HR No. / Back HR No. only.
 * Voucher No. is NOT generated here — it's entered manually (see addTransaction_).
 */
function generateHrNo_(type, dateObj) {
  const calYear = dateObj.getFullYear();
  const prefix = (type === 'Issue') ? 'ISS' : 'RET';
  const hrSeq = nextSeq_('HR_' + type + '_' + calYear);
  return prefix + '/' + pad_(hrSeq, 3) + '/BD-I';
}

/* ---------------- Write ---------------- */

/**
 * body = {
 *   action: 'addTransaction',
 *   date: 'YYYY-MM-DD',
 *   transactionType: 'Issue' | 'Receipt',
 *   schemeCode, schemeName,
 *   agencyDetails, workOrderDetails, nameOfWork,
 *   officeOrderNo, roadChallanNo,
 *   voucherNo,   // optional — fill in now if already known, or leave blank
 *   items: [{ itemCode, itemDescription, qty, unit }, ...]
 * }
 * Always writes to the CURRENT (live) Transactions tab.
 */
function addTransaction_(body) {
  if (!body.items || !body.items.length) throw new Error('At least one item line is required.');
  const sh = ensureSheet_(TXN_SHEET, TXN_HEADERS);
  const dateObj = new Date(body.date + 'T00:00:00');
  const hrNo = generateHrNo_(body.transactionType, dateObj);
  const now = new Date();
  let slNo = Math.max(0, sh.getLastRow() - 1);

  const rows = body.items.map(function (it, idx) {
    slNo += 1;
    return [
      slNo,
      body.date,
      body.transactionType,
      hrNo,
      body.schemeCode || '',
      body.schemeName || '',
      body.agencyDetails || '',
      body.workOrderDetails || '',
      body.nameOfWork || '',
      body.officeOrderNo || '',
      body.roadChallanNo || '',
      idx + 1,
      it.itemCode || '',
      it.itemDescription || '',
      Number(it.qty) || 0,
      it.unit || '',
      body.voucherNo || '',
      now
    ];
  });

  sh.getRange(sh.getLastRow() + 1, 1, rows.length, TXN_HEADERS.length).setValues(rows);
  invalidateReadCaches_();

  return { success: true, hrNo: hrNo, voucherNo: body.voucherNo || '', lines: rows.length };
}

/**
 * body = { action: 'updateVoucher', hrNo, voucherNo }
 * Fills in the Voucher No. (received later from the online system) for
 * every line already saved under a given HR No. Searches the live tab and
 * all archived Transactions_<year> tabs.
 */
function updateVoucher_(body) {
  if (!body.hrNo || !body.voucherNo) throw new Error('hrNo and voucherNo are both required.');
  const sheets = getAllTxnSheets_();
  let updated = 0;
  sheets.forEach(function (sh) {
    const rows = sheetRowsAsObjects_(sh);
    rows.forEach(function (r) {
      if (r['HRNo'] === body.hrNo) {
        sh.getRange(r.__row + 1, TXN_HEADERS.indexOf('VoucherNo') + 1).setValue(body.voucherNo);
        updated++;
      }
    });
  });
  if (!updated) throw new Error('No transaction found with HR No. ' + body.hrNo);
  invalidateReadCaches_();
  return { success: true, updated: updated };
}

/* ---------------- Read ---------------- */

/** All transaction sheets: the live "Transactions" tab plus any "Transactions_<year>" archives. */
function getAllTxnSheets_() {
  const ss = getSS();
  return ss.getSheets().filter(sh =>
    sh.getName() === TXN_SHEET || /^Transactions_\d{4}$/.test(sh.getName())
  );
}

function getAllTxns_() {
  const sheets = getAllTxnSheets_();
  let rows = [];
  sheets.forEach(function (sh) { rows = rows.concat(sheetRowsAsObjects_(sh)); });
  return rows;
}

function listTransactions_(params) {
  let rows = getAllTxns_();
  rows = applyFilters_(rows, params);
  rows.sort(byNewest);
  return { rows: rows, count: rows.length };
}

function applyFilters_(rows, params) {
  if (params.from) {
    const from = new Date(params.from);
    rows = rows.filter(function (r) { return new Date(r.Date) >= from; });
  }
  if (params.to) {
    const to = new Date(params.to);
    rows = rows.filter(function (r) { return new Date(r.Date) <= to; });
  }
  if (params.type) {
    rows = rows.filter(function (r) { return r.TransactionType === params.type; });
  }
  if (params.schemeCode) {
    rows = rows.filter(function (r) { return r.SchemeCode === params.schemeCode; });
  }
  if (params.itemCode) {
    rows = rows.filter(function (r) { return r.ItemCode === params.itemCode; });
  }
  if (params.noVoucherOnly === 'true') {
    rows = rows.filter(function (r) { return !r.VoucherNo; });
  }
  if (params.agency) {
    const q = params.agency.toLowerCase();
    rows = rows.filter(function (r) { return (r.AgencyDetails || '').toLowerCase().indexOf(q) > -1; });
  }
  if (params.workOrder) {
    const q = params.workOrder.toLowerCase();
    rows = rows.filter(function (r) { return (r.WorkOrderDetails || '').toLowerCase().indexOf(q) > -1; });
  }
  if (params.q) {
    const q = params.q.toLowerCase();
    rows = rows.filter(function (r) {
      return (r.AgencyDetails || '').toLowerCase().indexOf(q) > -1 ||
        (r.WorkOrderDetails || '').toLowerCase().indexOf(q) > -1 ||
        (r.NameOfWork || '').toLowerCase().indexOf(q) > -1 ||
        (r.ItemDescription || '').toLowerCase().indexOf(q) > -1 ||
        (r.HRNo || '').toLowerCase().indexOf(q) > -1 ||
        (r.VoucherNo || '').toLowerCase().indexOf(q) > -1;
    });
  }
  return rows;
}

/**
 * Stock register: opening balance (as of day before "from") + receipts - issues
 * within [from, to], per item. If itemCode given, restrict to that item.
 * Reads across the live tab and all archived year tabs, so balances stay
 * correct across a calendar-year rollover.
 * Results are cached server-side keyed by from|to|itemCode; the cache is
 * invalidated (version bump) on every write so it stays correct.
 * refresh=1 bypasses the cache read.
 */
function stockRegister_(params) {
  const cacheKey = 'sreg_v' + sregVersion_() + '_' +
    [params.from || '', params.to || '', params.itemCode || ''].join('|');
  return withCache_(cacheKey, params.refresh === '1', function () {
    return buildStockRegister_(params);
  });
}

/** Sort comparator: newest Date first, ties broken by highest SlNo first. */
function byNewest(a, b) {
  return new Date(b.Date) - new Date(a.Date) || b.SlNo - a.SlNo;
}

/** True when d is inside [from, to]; either bound may be null (open-ended). */
function isInRange_(d, from, to) {
  return (!from || d >= from) && (!to || d <= to);
}

function buildStockRegister_(params) {
  const rows = getAllTxns_();
  const from = params.from ? new Date(params.from) : null;
  const to = params.to ? new Date(params.to) : null;

  const byItem = {};
  rows.forEach(function (r) {
    if (params.itemCode && r.ItemCode !== params.itemCode) return;
    const key = r.ItemCode;
    if (!byItem[key]) {
      byItem[key] = {
        itemCode: r.ItemCode,
        description: r.ItemDescription,
        unit: r.Unit,
        opening: 0,
        received: 0,
        issued: 0,
        closing: 0,
        movements: []
      };
    }
    const d = new Date(r.Date);
    const qty = Number(r.Qty) || 0;
    const signed = (r.TransactionType === 'Receipt') ? qty : -qty;

    if (from && d < from) {
      byItem[key].opening += signed;
    } else if (isInRange_(d, from, to)) {
      if (r.TransactionType === 'Receipt') byItem[key].received += qty;
      else byItem[key].issued += qty;
      byItem[key].movements.push({
        date: r.Date, type: r.TransactionType, hrNo: r.HRNo, voucherNo: r.VoucherNo,
        agency: r.AgencyDetails, qty: qty
      });
    }
  });

  Object.keys(byItem).forEach(function (k) {
    const it = byItem[k];
    it.closing = it.opening + it.received - it.issued;
    it.movements.sort(function (a, b) { return new Date(a.date) - new Date(b.date); });
  });

  return { items: Object.values(byItem) };
}

/* ---------------- Filter options (transaction-derived dropdown values) ---------------- */

/**
 * Distinct values actually present in the transaction sheets, for the
 * movement-report / register dropdowns. Only values that have really been
 * transacted are offered — the master files (work orders, schemes) contain
 * far more than what the store has touched.
 * params: { refresh: '1' }.
 * Cached namespaced by sreg_ver so any write invalidates it (same rule as
 * the stock register).
 */
function filterOptions_(params) {
  const cacheKey = 'fopts_v' + sregVersion_() + '_all';
  return withCache_(cacheKey, params.refresh === '1', buildFilterOptions_);
}

function buildFilterOptions_() {
  const rows = getAllTxns_();
  const agencies = new Set();
  const workOrders = new Set();
  const schemes = {};
  rows.forEach(function (r) {
    const agency = String(r.AgencyDetails || '').trim();
    if (agency) agencies.add(agency);
    const wo = String(r.WorkOrderDetails || '').trim();
    if (wo) workOrders.add(wo);
    const code = String(r.SchemeCode || '').trim();
    if (code) schemes[code] = String(r.SchemeName || '');
  });
  const byName = function (a, b) { return a.localeCompare(b); };
  return {
    agencies: Array.from(agencies).sort(byName),
    workOrders: Array.from(workOrders).sort(byName),
    schemes: Object.keys(schemes).sort(byName).map(function (code) {
      return { schemeCode: code, schemeName: schemes[code] };
    })
  };
}

/* ---------------- Master data (external files, read-only) ---------------- */

function getMeta_(force) {
  return withCache_(CACHE_KEY_META, force, buildMeta_);
}

function buildMeta_() {
  const cfg = getConfigMap_();

  const itemTab = openExternalTab_(cfg['ItemMasterSheetId'], 'ItemMaster');
  const items = itemTab
    ? sheetRowsAsObjects_(itemTab)
        .map(r => ({ itemCode: r['ItemCode'], description: r['Description'], unit: r['Unit'] }))
        .filter(i => i.itemCode)
    : [];

  const schemeTab = openExternalTab_(cfg['SchemeMasterSheetId'], 'SchemeMaster');
  const schemes = schemeTab
    ? sheetRowsAsObjects_(schemeTab)
        .map(r => ({ schemeCode: r['SchemeCode'], schemeName: r['SchemeName'] }))
        .filter(s => s.schemeCode)
    : [];

  return { items: items, schemes: schemes, workOrderYears: getWorkOrderYears_(cfg) };
}

/** Calendar-year tabs (e.g. "2024", "2025", "2026") present in the Work Order Master file. */
function getWorkOrderYears_(cfg) {
  const id = cfg['WorkOrderMasterSheetId'];
  if (!id) return [];
  try {
    const ss = SpreadsheetApp.openById(extractSheetId_(id));
    return ss.getSheets()
      .map(s => s.getName())
      .filter(n => /^\d{4}$/.test(n))
      .sort()
      .reverse();
  } catch (err) {
    return [];
  }
}

/**
 * Returns ALL work-order rows for a calendar-year tab (no free-text filter).
 * The frontend downloads this once per year and searches it LOCALLY for
 * instant search. params: { year: '2026', refresh: '1' }.
 * Same row shape as searchWorkOrders_(), but unfiltered and cached.
 */
function workOrderIndex_(params) {
  const year = params.year;
  if (!year) throw new Error('year (calendar year, e.g. 2026) is required.');
  const tab = openWorkOrderTab_(String(year));
  if (!tab) return { rows: [], note: 'No tab named "' + year + '" found in the Work Order Master file.' };

  const cacheKey = 'woidx_' + year + '_v1';
  return withCache_(cacheKey, params.refresh === '1', function () {
    const rows = sheetRowsAsObjects_(tab)
      .map(function (r) {
        return {
          AgencyName: r['AgencyName'],
          WorkOrderNo: r['WorkOrderNo'],
          WorkOrderDate: r['WorkOrderDate'],
          NameOfWork: r['NameOfWork']
        };
      })
      .filter(function (r) { return r.WorkOrderNo; });
    return { rows: rows };
  });
}

/** Opens the given calendar-year tab of the Work Order Master, or null when missing/unconfigured. */
function openWorkOrderTab_(year) {
  const id = getConfigValue_('WorkOrderMasterSheetId');
  return id ? openExternalTab_(id, year) : null;
}

/**
 * Searches the calendar-year tab of the Work Order Master file for rows
 * matching a free-text query against agency name or work order no.
 * params: { year: '2026', q: 'jogmaya' }
 * Expected columns in each year's tab: AgencyName, WorkOrderNo, WorkOrderDate, NameOfWork
 * Kept as a fallback for the frontend when the local index can't load.
 */
function searchWorkOrders_(params) {
  const year = params.year;
  if (!year) throw new Error('year (calendar year, e.g. 2026) is required.');
  const tab = openWorkOrderTab_(String(year));
  if (!tab) return { rows: [], note: 'No tab named "' + year + '" found in the Work Order Master file.' };

  let rows = sheetRowsAsObjects_(tab);
  if (params.q) {
    const q = params.q.toLowerCase();
    rows = rows.filter(r =>
      String(r['AgencyName'] || '').toLowerCase().indexOf(q) > -1 ||
      String(r['WorkOrderNo'] || '').toLowerCase().indexOf(q) > -1 ||
      String(r['NameOfWork'] || '').toLowerCase().indexOf(q) > -1
    );
  }
  return { rows: rows.slice(0, 20) };
}

/* ---------------- Dashboard ---------------- */

function getDashboard_(force) {
  return withCache_(CACHE_KEY_DASH, force, buildDashboard_);
}

function buildDashboard_() {
  const rows = getAllTxns_();
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  let issuedQty = 0, receivedQty = 0, issuedLines = 0, receivedLines = 0;
  const issuedHrs = new Set(), receivedHrs = new Set();
  const stock = {};
  rows.forEach(function (r) {
    const d = new Date(r.Date);
    const qty = Number(r.Qty) || 0;
    if (d >= monthStart) {
      if (r.TransactionType === 'Issue') { issuedQty += qty; issuedLines++; }
      else { receivedQty += qty; receivedLines++; }
    }
    if (d.getFullYear() === now.getFullYear()) {
      if (r.TransactionType === 'Issue') issuedHrs.add(String(r.HRNo));
      else if (r.TransactionType === 'Receipt') receivedHrs.add(String(r.HRNo));
    }
    stock[r.ItemCode] = (stock[r.ItemCode] || 0) + (r.TransactionType === 'Receipt' ? qty : -qty);
  });
  let positiveStock = 0, negativeStock = 0;
  Object.keys(stock).forEach(function (k) {
    if (stock[k] > 0) positiveStock++;
    else if (stock[k] < 0) negativeStock++;
  });
  const pendingVoucher = rows.filter(function (r) { return !r.VoucherNo; }).length;
  const recent = rows
    .sort(byNewest)
    .slice(0, 8);
  return {
    monthIssuedQty: issuedQty, monthReceivedQty: receivedQty,
    monthIssuedLines: issuedLines, monthReceivedLines: receivedLines,
    yearIssuedHrs: issuedHrs.size, yearReceivedHrs: receivedHrs.size,
    positiveStock: positiveStock, negativeStock: negativeStock,
    totalTxns: rows.length, pendingVoucher: pendingVoucher, recent: recent
  };
}
